package sqlplus.springboot.dto;

/**
 * Currently, the name is generated by the server. This field is ignored.
 */
public class CompilePersistRequest {
    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
