SELECT
    T1.T_ID,
    T1.T_DTS,
    T1.T_TT_ID,
    T1.T_TRADE_PRICE,
    T2.T_ID,
    T2.T_DTS,
    T2.T_TT_ID,
    T2.T_TRADE_PRICE,
    T1.T_S_SYMB,
    T1.T_CA_ID
FROM Trade T1, Trade T2
WHERE T1.T_TT_ID LIKE '%B%' AND T2.T_TT_ID LIKE '%S%'
AND T1.T_CA_ID = T2.T_CA_ID
AND T1.T_S_SYMB = T2.T_S_SYMB
AND T1.T_DTS <= T2.T_DTS
AND T1.T_DTS + interval '90' day >= T2.T_DTS
AND T1.T_TRADE_PRICE * 1.2 < T2.T_TRADE_PRICE